import Head from "next/head";
// import styles from "@/styles/Home.module.css";
// import fonts from "../styles/fonts.css";
import Header from "../components/Header";
import HeaderIcons from "@/components/HeaderIcons";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="min-h-screen">
                <header>
                    <Header />
                    <div className="bg-[#4a96fb] rounded-[30px] mt-4 p-[80px] text-white">
                        <div className="text-[25px] pb-[40px]">
                            Помогаем детям
                        </div>
                        <div className="text-[80px]">
                            Помогаем детям по всему Казахстану
                        </div>
                    </div>
                    <HeaderIcons />
                </header>
                <div className="pt-[100px]">
                    <div className="text-[50px] pb-2">About Fund</div>
                    <div className="text-[22px]">
                        This fund is for butterfly sickness children
                    </div>
                    <div>Our mission and goal</div>
                </div>
            </div>
        </>
    );
}
