import Head from "next/head";
import Header from "../components/Header";
import HeaderIcons from "@/components/HeaderIcons";
import AboutFund from "@/components/AboutFund";
import HelpButton from "@/components/HelpButton";
import Children from "@/components/Children";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="min-h-screen">
                <header>
                    <Header />
                    <div className="bg-[#4a96fb] rounded-[30px] mt-4 p-[80px] text-white">
                        <div className="text-[25px] pb-[80px]">
                            Первый в Казахстане Фонд помощи детям с редким
                            генетическим заболеванием Буллёзный Эпидермолиз.
                        </div>
                        <div className="text-[80px] leading-none">
                            Дети бабочки Благотворительный фонд
                        </div>
                    </div>
                    <HeaderIcons />
                </header>
                <AboutFund />
                <HelpButton />
                <Children />
            </div>
        </>
    );
}
