import Head from "next/head";
import Header from "../components/Header/Header";
import HeaderIcons from "@/components/Header/HeaderIcons";
import AboutFund from "@/components/Fund/AboutFund";
import HelpButton from "@/components/HelpButton";
import Children from "@/components/Children";
import Footer from "../components/Footer";
import Statistics from "../components/Statistics";
import HeaderCard from "../components/Header/HeaderCard";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/logo.ico" />
            </Head>
            <div className="min-h-screen px-[15px] md:px-[30px] lg:px-[100px] xl:px-[200px] 2xl:px-[300px]">
                <header>
                    <Header />
                    <HeaderCard />
                    <HeaderIcons />
                </header>
                <AboutFund />
                <Statistics />
                <HelpButton />
                <Children />
            </div>
            <Footer />
        </>
    );
}
